// Source agencies
export const agencySources = [
  { value: "agencia_cygnus", label: "Agencia Cygnus" },
  { value: "agencia_bbn", label: "Agencia BBN" },
  { value: "agencia_peoplecare", label: "Agencia PeopleCare" },
  { value: "agencia_hq", label: "Agencia HQ" },
  { value: "agencia_stoneway", label: "Agencia Stoneway" }
];

// Genders
export const genders = [
  { value: "H", label: "H" },
  { value: "M", label: "M" },
  { value: "X", label: "X" }
];

// Nationalities
export const nationalities = [
  "México",
  "Guatemala",
  "Venezuela",
  "Colombia",
  "Honduras",
  "Cuba",
  "El Salvador",
  "Argentina",
  "Haití",
  "Nicaragua",
  "Perú",
  "Ecuador",
  "República Dominicana",
  "Brasil",
  "España",
  "Estados Unidos",
  "China",
  "India",
  "Egipto",
  "Irán",
  "Turquía",
  "Canadá"
];

// Positions
export const positions = [
  "Auxiliar de Administración",
  "Auxiliar General",
  "Auxiliar General de Perecederos",
  "Chofer Repartidor",
  "Mecánico",
  "Operador de Equipos de Carga",
  "Recibidor de Mercancía",
  "Jefatura Administrativa",
  "Jefatura de Calidad",
  "Jefatura de Operaciones de Logística",
  "Jefatura de Seguridad",
  "Jefatura de Transportes",
  "Jefatura de trato con proveedores",
  "Subgerencia en Entrenamiento"
];

// Locations
export const locations = [
  "Cedis ecommerce Walmart México",
  "Cedis Walmart BAE Sur - VESTA",
  "Cedis Walmart Chalco",
  "Cedis Walmart Chihuahua",
  "Cedis Walmart Cuautitlán",
  "Cedis Walmart ecommerce Guadalajara",
  "Cedis Walmart Guadalajara",
  "Cedis Walmart Merida",
  "Cedis Walmart Mexicali",
  "Cedis Walmart San Martin Obispo",
  "Cedis Walmart Santa Bárbara",
  "Centro de Distribucion Walmart Villahermosa",
  "Planta de Carnes Walmart Cuautitlán",
  "Walmart - CEDIS Monterrey",
  "Walmart Culiacan Cedis",
  "Walmart eCommerce MTY"
];

// Education levels
export const educationLevels = [
  "Primaria",
  "Secundaria",
  "Preparatoria",
  "Carrera Técnica",
  "Universidad",
  "Posgrado"
];

// Yes/No options
export const yesNoOptions = [
  { value: "Sí", label: "Sí" },
  { value: "No", label: "No" }
];

// Motivations
export const motivations = [
  "Cultura",
  "Compañía",
  "Líder",
  "Posición",
  "Sueldo",
  "Prestaciones",
  "Crecimiento",
  "Flexibilidad",
  "Ambiente"
];

// Mexican states
export const mexicanStates = [
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Chiapas",
  "Chihuahua",
  "Ciudad de México",
  "Coahuila",
  "Colima",
  "Durango",
  "Estado de México",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "Michoacán",
  "Morelos",
  "Nayarit",
  "Nuevo León",
  "Oaxaca",
  "Puebla",
  "Querétaro",
  "Quintana Roo",
  "San Luis Potosí",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz",
  "Yucatán",
  "Zacatecas"
];

// Municipios reales por estado
const municipalitiesByState: Record<string, string[]> = {
  "Aguascalientes": [
    "Aguascalientes",
    "Asientos",
    "Calvillo",
    "Cosío",
    "Jesús María",
    "Pabellón de Arteaga",
    "Rincón de Romos",
    "San José de Gracia",
    "Tepezalá",
    "El Llano",
    "San Francisco de los Romo"
  ],
  "Baja California": [
    "Ensenada",
    "Mexicali",
    "Tecate",
    "Tijuana",
    "Playas de Rosarito"
  ],
  "Baja California Sur": [
    "Comondú",
    "La Paz",
    "Loreto",
    "Los Cabos",
    "Mulegé"
  ],
  "Campeche": [
    "Calakmul",
    "Calkiní",
    "Campeche",
    "Candelaria",
    "Carmen",
    "Champotón",
    "Escárcega",
    "Hecelchakán",
    "Hopelchén",
    "Palizada",
    "Tenabo"
  ],
  "Chiapas": [
    "Acacoyagua",
    "Acala",
    "Acapetahua",
    "Aldama",
    "Altamirano",
    "Amatán",
    "Amatenango de la Frontera",
    "Amatenango del Valle",
    "Angel Albino Corzo",
    "Arriaga",
    "Bejucal de Ocampo",
    "Bella Vista",
    "Benemérito de las Américas",
    "Berriozábal",
    "Bochil",
    "Cacahoatán",
    "Catazajá",
    "Chalchihuitán",
    "Chamula",
    "Chanal",
    "Chapultenango",
    "Chenalhó",
    "Chiapa de Corzo",
    "Chiapilla",
    "Chicoasén",
    "Chicomuselo",
    "Chilón",
    "Cintalapa",
    "Coapilla",
    "Comitán de Dominguez",
    "Copainalá"
  ],
  "Chihuahua": [
    "Ahumada",
    "Aldama",
    "Allende",
    "Aquiles Serdán",
    "Ascensión",
    "Bachíniva",
    "Balleza",
    "Batopilas",
    "Bocoyna",
    "Buenaventura",
    "Camargo",
    "Carichi",
    "Casas Grandes",
    "Chihuahua",
    "Chínipas",
    "Coronado",
    "Coyame",
    "Cuauhtémoc",
    "Cusihuiriachi",
    "Delicias",
    "Dr. Belisario Domínguez",
    "Galeana",
    "Santa Isabel",
    "Gómez Farías",
    "Gran Morelos",
    "Guachochi",
    "Guadalupe",
    "Guadalupe y Calvo",
    "Guazapares",
    "Guerrero",
    "Hidalgo del Parral"
  ],
  "Ciudad de México": [
    "Alvaro Obregón",
    "Azcapotzalco",
    "Benito Juárez",
    "Coyoacán",
    "Cuajimalpa de Morelos",
    "Cuauhtémoc",
    "Gustavo A. Madero",
    "Iztacalco",
    "Iztapalapa",
    "La Magdalena Contreras",
    "Miguel Hidalgo",
    "Milpa Alta",
    "Tláhuac",
    "Tlalpan",
    "Venustiano Carranza",
    "Xochimilco"
  ],
  "Coahuila": [
    "Abasolo",
    "Acuña",
    "Allende",
    "Arteaga",
    "Candela",
    "Castaños",
    "Cuatrociénegas",
    "Escobedo",
    "Francisco I. Madero",
    "Frontera",
    "General Cepeda",
    "Guerrero",
    "Hidalgo",
    "Jiménez",
    "Juárez",
    "Lamadrid",
    "Matamoros",
    "Monclova",
    "Morelos",
    "Múzquiz",
    "Nadadores",
    "Nava",
    "Ocampo",
    "Parras",
    "Piedras Negras",
    "Progreso",
    "Ramos Arizpe",
    "Sabinas",
    "Sacramento",
    "Saltillo",
    "San Buenaventura",
    "San Juan de Sabinas",
    "San Pedro",
    "Sierra Mojada",
    "Torreón",
    "Viesca",
    "Villa Unión",
    "Zaragoza"
  ],
  "Colima": [
    "Armería",
    "Colima",
    "Comala",
    "Coquimatlán",
    "Cuauhtémoc",
    "Ixtlahuacán",
    "Manzanillo",
    "Minatitlán",
    "Tecomán",
    "Villa de Alvarez"
  ],
  "Durango": [
    "Canatlán",
    "Canelas",
    "Coneto de Comonfort",
    "Cuencamé",
    "Durango",
    "El Oro",
    "General Simón Bolívar",
    "Gómez Palacio",
    "Guadalupe Victoria",
    "Guanaceví",
    "Hidalgo",
    "Indé",
    "Lerdo",
    "Mapimí",
    "Mezquital",
    "Nazas",
    "Nombre de Dios",
    "Ocampo",
    "Otáez",
    "Pánuco de Coronado",
    "Peñón Blanco",
    "Poanas",
    "Pueblo Nuevo",
    "Rodeo",
    "San Bernardo",
    "San Dimas",
    "San Juan de Guadalupe",
    "San Juan del Río",
    "San Luis del Cordero",
    "San Pedro del Gallo",
    "Santa Clara",
    "Santiago Papasquiaro",
    "Súchil",
    "Tamazula",
    "Tepehuanes",
    "Tlahualilo",
    "Topia",
    "Vicente Guerrero"
  ],
  "Estado de México": [
    "Acambay",
    "Acolman",
    "Aculco",
    "Almoloya de Alquisiras",
    "Almoloya de Juárez",
    "Almoloya del Río",
    "Amanalco",
    "Amatepec",
    "Amecameca",
    "Apaxco",
    "Atizapán de Zaragoza",
    "Atizapán",
    "Atlacomulco",
    "Atlautla",
    "Axapusco",
    "Ayapango",
    "Calimaya",
    "Capulhuac",
    "Coacalco de Berriozábal",
    "Coatepec Harinas",
    "Cocotitlán",
    "Coyotepec",
    "Cuautitlán",
    "Chalco",
    "Chapa de Mota",
    "Chapultepec",
    "Chiautla",
    "Chicoloapan",
    "Chiconcuac",
    "Chimalhuacán",
    "Donato Guerra",
    "Ecatepec de Morelos",
    "Ecatzingo",
    "Huehuetoca",
    "Hueypoxtla",
    "Huixquilucan",
    "Isidro Fabela",
    "Ixtapaluca",
    "Ixtapan de la Sal",
    "Ixtapan del Oro",
    "Ixtlahuaca",
    "Xalatlaco",
    "Xonacatlán",
    "Jaltenco",
    "Jilotepec",
    "Jilotzingo",
    "Jiquipilco",
    "Jocotitlán",
    "Joquicingo",
    "Juchitepec",
    "La Paz",
    "Lerma",
    "Malinalco",
    "Melchor Ocampo",
    "Metepec",
    "Mexicaltzingo",
    "Morelos",
    "Naucalpan de Juárez",
    "Nezahualcóyotl",
    "Nextlalpan",
    "Nicolás Romero",
    "Nopaltepec",
    "Ocoyoacac",
    "Ocuilan",
    "El Oro",
    "Otumba",
    "Otzoloapan",
    "Otzolotepec",
    "Ozumba",
    "Papalotla",
    "Polotitlán",
    "Rayón",
    "San Antonio la Isla",
    "San Felipe del Progreso",
    "San Martín de las Pirámides",
    "San Mateo Atenco",
    "San Simón de Guerrero",
    "Santo Tomás",
    "Soyaniquilpan de Juárez",
    "Sultepec",
    "Tecámac",
    "Tejupilco",
    "Temamatla",
    "Temascalapa",
    "Temascalcingo",
    "Temascaltepec",
    "Temoaya",
    "Tenancingo",
    "Tenango del Aire",
    "Tenango del Valle",
    "Teoloyucan",
    "Teotihuacán",
    "Tepetlaoxtoc",
    "Tepetlixpa",
    "Tepotzotlán",
    "Tequixquiac",
    "Texcaltitlán",
    "Texcalyacac",
    "Texcoco",
    "Tezoyuca",
    "Tianguistenco",
    "Timilpan",
    "Tlalmanalco",
    "Tlalnepantla de Baz",
    "Tlatlaya",
    "Toluca",
    "Tonatico",
    "Tultepec",
    "Tultitlán",
    "Valle de Bravo",
    "Valle de Chalco Solidaridad",
    "Villa de Allende",
    "Villa del Carbón",
    "Villa Guerrero",
    "Villa Victoria",
    "Xonacatlán",
    "Zacazonapan",
    "Zacualpan",
    "Zinacantepec",
    "Zumpahuacán",
    "Zumpango"
  ]
};

export function getMunicipalitiesForState(state: string): string[] {
  return municipalitiesByState[state] || [];
}

// Marital statuses
export const maritalStatuses = [
  "Soltera/o",
  "Casada/o",
  "Viudo",
  "Divorciado/a",
  "Separado",
  "Unión libre"
];

// Disability types
export const disabilityTypes = [
  "DISCAPACIDAD LENGUAJE O HABLA",
  "DISCAPACIDAD MOTRIZ",
  "DISCAPACIDAD VISUAL",
  "DISCAPACIDAD AUDITIVA",
  "DISCAPACIDAD INTELECTUAL"
];

// Emergency contact relations
export const emergencyContactRelations = [
  "Cónyuge",
  "Cónyuge divorciado",
  "Hijo",
  "Padres",
  "Hermanos",
  "Otros",
  "Otros parientes"
];

// Dependent relations
export const dependentRelations = [
  "Cónyuge",
  "Cónyuge divorciado",
  "Padre",
  "Madre",
  "Pareja en unión libre",
  "Hijo de pareja en unión libre",
  "Hermano",
  "Hermana",
  "Pareja en unión libre registrada",
  "Hijo",
  "Tutor legal",
  "Tutor",
  "Hijastro",
  "Personas emparentadas"
];
